services:
  php8.2:
    container_name: 'docker_php8.2'
    build:
      context: src/php8.2
    hostname: php8.2
    ports:
      - "10000:9000"
      - "6000:6000"
      - "5173:5173"
    volumes:
      - ../projects/:/var/www/html/
      - ./src/php8.2/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src/php8.2/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  php8.3:
    container_name: 'docker_php8.3'
    build:
      context: src/php8.3
    hostname: php8.3
    ports:
      - "10001:9000"
      - "6001:6001"
      - "5174:5174"
    volumes:
      - ../projects/:/var/www/html/
      - ./src/php8.3/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src/php8.3/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  vuejs:
    container_name: 'docker_vuejs'
    build:
      context: ../projects/vue-app
    ports:
      - "8081:8080"
    volumes:
      - ../projects/vue-app:/var/www/html/vue-app
      - /var/www/html/vue-app/node_modules
    networks:
      - backend
  nginx:
    container_name: 'docker_nginx'
    platform: linux/amd64 # for mac
    image: nginx:alpine
    ports:
      - "80:80"
      - "8000:8000"
      - "8888:8888"
    volumes:
      - ../projects/:/var/www/html/
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8.2
      - php8.3
      - vuejs
    networks:
      - backend
  mysql:
    container_name: 'docker_mysql'
    platform: linux/amd64 # for mac
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    depends_on:
      - php8.2
      - php8.3
    volumes:
      - ./src/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
  phpmyadmin:
    container_name: 'docker_phpmyadmin'
    platform: linux/amd64 # for mac
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PASSWORD: "12345678"
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - backend
  redis:
    container_name: 'docker_redis'
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./src/redis:/data
    networks:
      - backend
  redisui:
    container_name: 'docker_redis_ui'
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - "7843:7843"
    volumes:
      - ./src/p3x-redis-ui-settings:/settings
    networks:
      - backend
  elastic:
    container_name: 'docker_elastic'
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - elastic_container=true
    networks:
      - backend
networks:
  backend:
    driver: bridge